### ISSUE TITLE
Cross-Platform CMake support

### ISSUE THREAD

**Issue by epraekelt** [epraekelt/cs-foundations#3]
Seeking to automate the compilation process with CMake to support Linux, Windows and Mac.

**Comment by ghost** [comment]
I guess I can pick this up, I'll get to it once I have some free time.

**Comment by ghost** [comment]
Any reason for cmake specifically?

**Comment by epraekelt** [comment]
@QingYun, since you mentioned this idea to me, do you want to discuss and coordinate with @RenegadeTech on this?

**Comment by QingYun** [comment]
almost missed this... cmake is mainly for Windows support, but since the UI part doesn't have the renderer implementation for Windows I guess we can forget about this for the moment.

**Comment by epraekelt** [comment]
Since we've moved completely to web framework, this is now obsolete, so I'm closing it.
